/**
 * YouTube Service
 * Handles YouTube video metadata extraction and caption download using YouTube.js
 */

import { Innertube } from 'youtubei.js';
import type { VideoMetadata } from '../types';

export interface YouTubeCaptionTrack {
	text: string;
	language: string;
	isAutoGenerated: boolean;
}

export class YouTubeService {
	private innertube: Innertube | null = null;

	/**
	 * Initialize the YouTube InnerTube client
	 */
	async initialize(): Promise<void> {
		if (this.innertube) {
			return; // Already initialized
		}

		try {
			this.innertube = await Innertube.create({
				lang: 'en',
				location: 'US',
				retrieve_player: true,
			});
		} catch (error) {
			console.error('Failed to initialize YouTube service:', error);
			throw new Error(`Failed to initialize YouTube service: ${error.message}`);
		}
	}

	/**
	 * Fetch video metadata from YouTube
	 */
	async getVideoMetadata(videoId: string): Promise<VideoMetadata> {
		await this.initialize();

		if (!this.innertube) {
			throw new Error('YouTube service not initialized');
		}

		try {
			const info = await this.innertube.getInfo(videoId);

			// Extract basic info
			const basicInfo = info.basic_info;
			const title = basicInfo.title || 'Unknown Title';
			const duration = basicInfo.duration || 0;

			// Language detection from captions if available
			let language = 'en';
			if (info.captions && info.captions.caption_tracks && info.captions.caption_tracks.length > 0) {
				language = info.captions.caption_tracks[0].language_code || 'en';
			}

			// Check if captions are available
			const hasCaptions = (info.captions?.caption_tracks?.length || 0) > 0;

			const metadata: VideoMetadata = {
				videoId,
				title,
				duration,
				language,
				url: `https://www.youtube.com/watch?v=${videoId}`,
				hasYouTubeCaptions: hasCaptions,
			};

			return metadata;
		} catch (error: any) {
			console.error('Error fetching video metadata:', error);
			throw new Error(`Failed to fetch video metadata: ${error?.message || error}`);
		}
	}

	/**
	 * Download YouTube captions/transcripts
	 * Returns the caption track in the original language (not auto-translated)
	 */
	async getCaptions(videoId: string): Promise<YouTubeCaptionTrack | null> {
		await this.initialize();

		if (!this.innertube) {
			throw new Error('YouTube service not initialized');
		}

		try {
			const info = await this.innertube.getInfo(videoId);
			const captions = info.captions;

			if (!captions || !captions.caption_tracks || captions.caption_tracks.length === 0) {
				return null; // No captions available
			}

			// Get video's original language from caption tracks
			const tracks = captions.caption_tracks;

			// Prefer manually created captions over auto-generated
			let selectedTrack = tracks.find((track) => track.kind !== 'asr');

			// If no manual captions, use auto-generated
			if (!selectedTrack) {
				selectedTrack = tracks.find((track) => track.kind === 'asr');
			}

			// If still no match, use the first available caption track
			if (!selectedTrack) {
				selectedTrack = tracks[0];
			}

			if (!selectedTrack) {
				return null;
			}

			// For now, return a simplified caption response
			// YouTube.js API for getting actual transcript text varies by version
			// This can be enhanced later with proper transcript fetching
			return {
				text: `Captions available in language: ${selectedTrack.language_code}\nNote: Full caption download will be implemented in a future update.`,
				language: selectedTrack.language_code || 'en',
				isAutoGenerated: selectedTrack.kind === 'asr',
			};
		} catch (error: any) {
			console.error('Error fetching captions:', error);
			throw new Error(`Failed to fetch captions: ${error?.message || error}`);
		}
	}

	/**
	 * Get downloadable audio stream URL
	 * Returns the highest quality audio-only format
	 */
	async getAudioStreamUrl(videoId: string): Promise<string> {
		await this.initialize();

		if (!this.innertube) {
			throw new Error('YouTube service not initialized');
		}

		try {
			const info = await this.innertube.getInfo(videoId);

			// Get streaming data
			const streamingData = info.streaming_data;
			if (!streamingData) {
				throw new Error('No streaming data available');
			}

			// Get adaptive formats (separate audio and video)
			const adaptiveFormats = streamingData.adaptive_formats || [];

			// Filter for audio-only formats
			const audioFormats = adaptiveFormats.filter((format: any) => {
				return format.has_audio && !format.has_video;
			});

			if (audioFormats.length === 0) {
				throw new Error('No audio-only formats available');
			}

			// Sort by bitrate (highest first) and select the best
			audioFormats.sort((a: any, b: any) => (b.bitrate || 0) - (a.bitrate || 0));
			const bestAudio = audioFormats[0];

			if (!bestAudio.url) {
				throw new Error('Audio format has no URL');
			}

			return bestAudio.url;
		} catch (error) {
			console.error('Error getting audio stream URL:', error);
			throw new Error(`Failed to get audio stream: ${error.message}`);
		}
	}

	/**
	 * Format seconds to MM:SS or HH:MM:SS
	 */
	private formatTimestamp(seconds: number): string {
		const hours = Math.floor(seconds / 3600);
		const minutes = Math.floor((seconds % 3600) / 60);
		const secs = Math.floor(seconds % 60);

		if (hours > 0) {
			return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
		} else {
			return `${minutes}:${secs.toString().padStart(2, '0')}`;
		}
	}
}
